<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
    	<a href="<?php echo $block->getBaseUrl(); ?>blog/index/create" class="btn btn-primary btn-xs pull-right">Create New Post</a>
	  	<tr>
		    <th>Id</th>
		    <th>Name</th>
		    <th>Url Key</th>
		    <th>Image</th>
		    <th>Content</th>
		    <th>Status</th>
		    <th>Creared At</th>
		    <th>Updated At</th>
		    <th></th>
		    <th></th>
	    </tr>
    </thead>
    <?php
    $posts = $block->getPosts();
    foreach ($posts as $post) {
    	echo "<tr style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">";
    	echo "<td>".$post->getId()."</td>";
    	echo "<td>".$post->getName()."</td>";
    	echo "<td>".$post->getUrlKey()."</td>";
    	echo "<td>".$post->getImage()."</td>";
    	echo "<td>".$post->getContent()."</td>";
    	echo "<td>".$post->getStatus()."</td>";
    	echo "<td>".$post->getCreatedAt()."</td>";
    	echo "<td>".$post->getUpdatedAt()."</td>";
        echo '<td><a href="'. $block->getBaseUrl().'blog/index/edit/post_id/'.$post->getId().'"  class="btn btn-primary btn-xs pull-right">Edit</a></td>';
    	echo '<td><a href="'. $block->getBaseUrl().'blog/index/delete/post_id/'.$post->getId().'"  class="btn btn-danger btn-xs pull-right">Delete</a></td>';
    	echo "</tr>";
    }
    ?>
</table>